In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

In [2]:
import pandas as pd
# import numpy as np

# import yfinance as yf

# import altair as alt

from utils.nse_classification import INDUSTRY_STANDARDIZATION

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
SYMBOL_TO_COMPANY= {"IDFC": "Infrastructure Development Finance Co. Ltd.", "INFY": "Infosys Ltd.", "ITC": "ITC Ltd.", "SAIL": "Steel Authority of India Ltd."}

In [4]:
COMPANY_TO_SYMBOL= {"Bajaj Auto Ltd.": "BAJAJAUTO", "Eternal Ltd.": "ETERNAL", 
 "Infosys Technologies Ltd.": "INFY", "Reliance Infrastructure Ltd.": "RELINFRA",
 "Tata Communications Ltd.": "TATACOMM", "Vedanta Ltd.": "VEDL"}

In [5]:
COMPANY_NAME_STANDARDIZATION = {
    "Infosys Technologies Ltd.": "Infosys Ltd.",
    "Hero Honda Motors Ltd.": "Hero MotoCorp Ltd.",
    "Sterlite Industries (India) Ltd.": "Vedanta Ltd.",
    "Sesa Goa Ltd.": "Vedanta Ltd.",
    "IT C Ltd.": "ITC Ltd.",
}

In [6]:
nifty50= (
    pd.read_parquet(
        "../data/processed/nifty50_history.parquet",
        # parse_dates=["Date"],
    )
    .assign(
            symbol= lambda df_: df_["company_name"].map(COMPANY_TO_SYMBOL).fillna(df_["symbol"]),
            company_name= lambda df_: (
                df_["symbol"]
                .map(SYMBOL_TO_COMPANY).fillna(df_["company_name"])
                # .map(COMPANY_NAME_STANDARDIZATION).fillna(df_["company_name"])
            ),
            industry_= lambda df_: (
                df_["industry"]
                .astype(str)
                .str.strip()
                .str.replace(r"\s+", " ", regex=True)
                .map(INDUSTRY_STANDARDIZATION)
            )
    )
    # .assign(
    #     company_name= lambda df_: (
    #         df_["company_name"].map(COMPANY_NAME_STANDARDIZATION).fillna(df_["company_name"])
    #     )
    # )
)

nifty50.head()

,rank,symbol,company_name,industry,equity_capital,free_float_market_cap,weight,beta,r2,volatility,monthly_return,impact_cost,report_date,source_file,industry_
0,1,ABB,ABB Ltd.,Electrical Equipment,4.238168e+08,23732.0,0.80,0.86,0.48,3.14,-25.94,0.15,2008-01-01,nifty50_jan08.csv,Heavy Electrical Equipment
1,2,ACC,ACC Ltd.,Cement & Cement Products,1.876243e+09,14411.0,0.49,0.89,0.36,3.73,-25.05,0.17,2008-01-01,nifty50_jan08.csv,Cement & Cement Products
2,3,BAJAJAUTO,Bajaj Auto Ltd.,Automobiles - 2 and 3 wheelers,1.011835e+09,23870.0,0.80,0.64,0.25,4.75,-10.23,0.17,2008-01-01,nifty50_jan08.csv,Two & Three Wheelers
3,4,BHARTIARTL,Bharti Airtel Ltd.,Telecommunication - Services,1.897883e+10,163000.0,5.49,0.89,0.42,3.08,-13.80,0.15,2008-01-01,nifty50_jan08.csv,Telecom Services
4,5,BHEL,Bharat Heavy Electricals Ltd.,Electrical Equipment,4.895200e+09,100856.0,3.40,1.10,0.58,3.34,-20.44,0.11,2008-01-01,nifty50_jan08.csv,Heavy Electrical Equipment

In [7]:
(
    nifty50["industry_"].isna().sum()
)

np.int64(0)

In [8]:
(
    nifty50
    .query("industry_.isna()")
    ["industry"]
    .unique()
    .tolist()
)

[]

In [ ]:
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   compile.py
        modified:   data/processed/nifty50_history.csv
        modified:   data/processed/nifty50_history.parquet
        modified:   utils/columns.py
        modified:   utils/constants.py
        modified:   utils/loader.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        notebooks/
        research/
        utils/historical_information.py
        utils/nse_classification.py

no changes added to commit (use "git add" and/or "git commit -a")

In [ ]:
modified compile.py, added historical_information and nse_classification for company classification, added nse industry classification handbook

In [9]:
nifty50.company_name.unique()#.to_list()

<ArrowStringArray>
[                           'ABB Ltd.',                            'ACC Ltd.',
                     'Bajaj Auto Ltd.',                  'Bharti Airtel Ltd.',
       'Bharat Heavy Electricals Ltd.',   'Bharat Petroleum Corporation Ltd.',
                          'Cipla Ltd.',                           'NTPC Ltd.',
       'Dr. Reddy's Laboratories Ltd.',                   'GAIL (India) Ltd.',
 ...
              'Adani Enterprises Ltd.',                    'LTIMindtree Ltd.',
                'Shriram Finance Ltd.',             'Bharat Electronics Ltd.',
                          'Trent Ltd.',                        'Eternal Ltd.',
         'Jio Financial Services Ltd.',            'InterGlobe Aviation Ltd.',
       'Max Healthcare Institute Ltd.', 'Tata Motors Passenger Vehicles Ltd.']
Length: 105, dtype: str

In [9]:
# nifty50.query("company_name== 'Infosys Technologies Ltd.'")

In [10]:
nifty50.isna().sum()

rank                        0
symbol                      0
company_name                0
industry                 3060
equity_capital              0
free_float_market_cap       0
weight                      0
beta                        0
r2                          0
volatility                  0
monthly_return              3
impact_cost                 0
report_date                 0
source_file                 0
dtype: int64

In [11]:
nifty50.info()

<class 'pandas.DataFrame'>
RangeIndex: 11050 entries, 0 to 11049
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   rank                   11050 non-null  int64
 1   symbol                 11050 non-null  str
 2   company_name           11050 non-null  str
 3   industry               7990 non-null   str
 4   equity_capital         11050 non-null  float64
 5   free_float_market_cap  11050 non-null  float64
 6   weight                 11050 non-null  float64
 7   beta                   11050 non-null  float64
 8   r2                     11050 non-null  float64
 9   volatility             11050 non-null  float64
 10  monthly_return         11047 non-null  float64
 11  impact_cost            11050 non-null  float64
 12  report_date            11050 non-null  datetime64[us]
 13  source_file            11050 non-null  str
dtypes: datetime64[us](1), float64(8), int64(1), str(4)
memory usage: 1.8 MB

In [12]:
nifty50.describe()

,rank,equity_capital,free_float_market_cap,weight,beta,r2,volatility,monthly_return,impact_cost,report_date
count,11050.000000,1.105000e+04,1.105000e+04,11050.000000,11050.000000,11050.000000,11050.000000,11047.000000,11050.000000,11050
mean,25.500000,1.175355e+10,9.364043e+04,2.246086,0.993132,0.311630,1.898686,0.941789,0.047345,2017-03-15 04:27:08.959276
min,1.000000,1.547098e+08,2.534000e+03,0.090000,-0.020000,-0.010000,-0.711645,-70.810000,0.000000,2008-01-01 00:00:00
25%,13.000000,1.609371e+09,2.228187e+04,0.720000,0.720000,0.182817,1.270000,-4.494109,0.020000,2012-08-01 00:00:00
50%,25.500000,3.618088e+09,4.664136e+04,1.100000,0.960000,0.300000,1.650000,0.540000,0.030000,2017-03-01 00:00:00
75%,38.000000,1.032013e+10,9.975718e+04,2.310000,1.240000,0.425982,2.190000,6.230000,0.070000,2021-11-01 00:00:00
max,50.000000,1.353254e+11,1.534634e+06,249.570000,2.860000,0.840000,16.630000,82.970000,0.330000,2026-06-01 00:00:00
std,14.431523,2.021190e+10,1.444166e+05,5.867038,0.371912,0.161628,1.066160,10.307722,0.033313,NaN

In [13]:
nifty50.describe(include= "str")

,symbol,company_name,industry,source_file
count,11050,11050,7990,11050
unique,105,105,26,221
top,BHARTIARTL,Bharti Airtel Ltd.,Computers - Software & Consulting,nifty50_jan08.csv
freq,221,221,1049,50

In [14]:
(
    nifty50
    .groupby("company_name", as_index= False)
    .size()
    .sort_values("size", ascending= False)
    [:10]
    # .query("size== 221")
    # .shape
    # [["company_name"]]
    # .unique()
)

                company_name  size
16        Bharti Airtel Ltd.   221
40           ICICI Bank Ltd.   221
31     HCL Technologies Ltd.   221
38   Hindustan Unilever Ltd.   221
36  Hindalco Industries Ltd.   221
21                Cipla Ltd.   221
32            HDFC Bank Ltd.   221
46              Infosys Ltd.   221
41                  ITC Ltd.   221
57  Mahindra & Mahindra Ltd.   221

In [15]:
li= (
    nifty50
    .groupby("symbol", as_index= False)
    .agg(
        {"company_name":  "nunique"}
    )
    # .sort_values("company_name", ascending= False)
    .query("company_name> 1")
    ["symbol"]
    .to_list()
)
li

[]

In [16]:
(
    nifty50
    .groupby(["symbol", "company_name"], as_index= False)
    .size()
    # .groupby("symbol", as_index= False)
    # .
    .query("symbol in @li")
    ["company_name"]
    .unique()
)

<ArrowStringArray>
[]
Length: 0, dtype: str

In [17]:
(
    nifty50
    .assign(
        company_name= lambda df_: df_["symbol"].map(SYMBOL_TO_COMPANY).fillna(df_["company_name"])
    )
    .query(
        "symbol in @li"
    )
    # .query("symbol in @li")
    ["company_name"]
    .unique()
)

<ArrowStringArray>
[]
Length: 0, dtype: str

In [18]:
li= (
    nifty50
    .groupby("company_name", as_index= False)
    .agg(
        {"symbol":  "nunique"}
    )
    # .sort_values("company_name", ascending= False)
    .query("symbol> 1")
    ["company_name"]
    .to_list()
)
li

[]

In [19]:
(
    nifty50
    .groupby(["company_name", "symbol"], as_index= False)
    .size()
    .query("company_name in @li")
)

Empty DataFrame
Columns: [company_name, symbol, size]
Index: []

In [20]:
(
    nifty50
    .assign(
        symbol= lambda df_: df_["company_name"].map(SYMBOL_TO_COMPANY).fillna(df_["company_name"])
    )
    .query(
        "company_name in @li"
    )
    # .query("symbol in @li")
    ["company_name"]
    .unique()
)

<ArrowStringArray>
[]
Length: 0, dtype: str

In [21]:
li= (
    nifty50
    .groupby("symbol", as_index= False)
    .agg(
        {"industry":  "nunique"}
    )
    # .sort_values("company_name", ascending= False)
    .query("industry> 1")
    ["symbol"]
    .to_list()
)
li

['AXISBANK',
 'BAJAJFINSV',
 'BAJFINANCE',
 'COALINDIA',
 'EICHERMOT',
 'HDFCBANK',
 'HDFCLIFE',
 'ICICIBANK',
 'INDUSINDBK',
 'KOTAKBANK',
 'NTPC',
 'POWERGRID',
 'SAIL',
 'SBILIFE',
 'VEDL']

In [22]:
li= (
    nifty50
    .groupby("company_name", as_index= False)
    .agg(
        {"industry":  "nunique"}
    )
    # .sort_values("company_name", ascending= False)
    .query("industry> 1")
    ["company_name"]
    .to_list()
)
li

['Axis Bank Ltd.',
 'Bajaj Finance Ltd.',
 'Bajaj Finserv Ltd.',
 'Coal India Ltd.',
 'Eicher Motors Ltd.',
 'HDFC Bank Ltd.',
 'HDFC Life Insurance Company Ltd.',
 'ICICI Bank Ltd.',
 'IndusInd Bank Ltd.',
 'Kotak Mahindra Bank Ltd.',
 'NTPC Ltd.',
 'Power Grid Corporation of India Ltd.',
 'SBI Life Insurance Company Ltd.',
 'Steel Authority of India Ltd.',
 'Vedanta Ltd.']

In [23]:
len(li)

15

In [24]:
len(li)

15

In [25]:
nifty50["company_name"].unique().tolist()

['ABB Ltd.',
 'ACC Ltd.',
 'Bajaj Auto Ltd.',
 'Bharti Airtel Ltd.',
 'Bharat Heavy Electricals Ltd.',
 'Bharat Petroleum Corporation Ltd.',
 'Cipla Ltd.',
 'NTPC Ltd.',
 "Dr. Reddy's Laboratories Ltd.",
 'GAIL (India) Ltd.',
 'GlaxoSmithKline Pharmaceuticals Ltd.',
 'Grasim Industries Ltd.',
 'Ambuja Cements Ltd.',
 'HCL Technologies Ltd.',
 'Housing Development Finance Corporation Ltd.',
 'HDFC Bank Ltd.',
 'Hero Honda Motors Ltd.',
 'Hindalco Industries Ltd.',
 'Hindustan Unilever Ltd.',
 'Cairn India Ltd.',
 'ICICI Bank Ltd.',
 'Infosys Ltd.',
 'Unitech Ltd.',
 'ITC Ltd.',
 'Reliance Petroleum Ltd.',
 'Larsen & Toubro Ltd.',
 'Maruti Suzuki India Ltd.',
 'Mahindra & Mahindra Ltd.',
 'Idea Cellular Ltd.',
 'National Aluminium Co. Ltd.',
 'Oil & Natural Gas Corporation Ltd.',
 'Sterlite Industries (India) Ltd.',
 'Punjab National Bank',
 'Ranbaxy Laboratories Ltd.',
 'Reliance Infrastructure Ltd.',
 'Reliance Industries Ltd.',
 'Steel Authority of India Ltd.',
 'Satyam Computer Services Ltd.',
 'State Bank of India',
 'Siemens Ltd.',
 'Sun Pharmaceutical Industries Ltd.',
 'Suzlon Energy Ltd.',
 'Tata Power Co. Ltd.',
 'Reliance Communications Ltd.',
 'Tata Motors Ltd.',
 'Tata Consultancy Services Ltd.',
 'Tata Steel Ltd.',
 'Tata Communications Ltd.',
 'Wipro Ltd.',
 'Zee Entertainment Enterprises Ltd.',
 'DLF Ltd.',
 'Power Grid Corporation of India Ltd.',
 'Reliance Power Ltd.',
 'Reliance Capital Ltd.',
 'Axis Bank Ltd.',
 'Jindal Steel & Power Ltd.',
 'Infrastructure Development Finance Co. Ltd.',
 'Jaiprakash Associates Ltd.',
 'Kotak Mahindra Bank Ltd.',
 'Sesa Goa Ltd.',
 'Hero MotoCorp Ltd.',
 'Coal India Ltd.',
 'Asian Paints Ltd.',
 'Bank of Baroda',
 'Lupin Ltd.',
 'UltraTech Cement Ltd.',
 'Vedanta Ltd.',
 'IndusInd Bank Ltd.',
 'NMDC Ltd.',
 'Sesa Sterlite Ltd.',
 'United Spirits Ltd.',
 'Tech Mahindra Ltd.',
 'Yes Bank Ltd.',
 'Bosch Ltd.',
 'Adani Ports and Special Economic Zone Ltd.',
 'Aurobindo Pharma Ltd.',
 'Bharti Infratel Ltd.',
 'Eicher Motors Ltd.',
 'Tata Motors Ltd DVR',
 'Indiabulls Housing Finance Ltd.',
 'Indian Oil Corporation Ltd.',
 'Bajaj Finance Ltd.',
 'Hindustan Petroleum Corporation Ltd.',
 'UPL Ltd.',
 'Bajaj Finserv Ltd.',
 'Titan Company Ltd.',
 'JSW Steel Ltd.',
 'Britannia Industries Ltd.',
 'Nestle India Ltd.',
 'Shree Cement Ltd.',
 'HDFC Life Insurance Company Ltd.',
 "Divi's Laboratories Ltd.",
 'SBI Life Insurance Company Ltd.',
 'Tata Consumer Products Ltd.',
 'Apollo Hospitals Enterprise Ltd.',
 'Adani Enterprises Ltd.',
 'LTIMindtree Ltd.',
 'Shriram Finance Ltd.',
 'Bharat Electronics Ltd.',
 'Trent Ltd.',
 'Eternal Ltd.',
 'Jio Financial Services Ltd.',
 'InterGlobe Aviation Ltd.',
 'Max Healthcare Institute Ltd.',
 'Tata Motors Passenger Vehicles Ltd.']

In [26]:
(
    nifty50
    .assign(
        industry= lambda df_: df_["symbol"].map(SYMBOL_TO_COMPANY).fillna(df_["company_name"])
    )
    .query(
        "symbol in @li"
    )
    # .query("symbol in @li")
    ["company_name"]
    .unique()
    # .tolist()
)

<ArrowStringArray>
[]
Length: 0, dtype: str

In [27]:
(
    nifty50
    ["symbol"]
    .unique()
    .tolist()
)

['ABB',
 'ACC',
 'BAJAJAUTO',
 'BHARTIARTL',
 'BHEL',
 'BPCL',
 'CIPLA',
 'NTPC',
 'DRREDDY',
 'GAIL',
 'GLAXO',
 'GRASIM',
 'AMBUJACEM',
 'HCLTECH',
 'HDFC',
 'HDFCBANK',
 'HEROHONDA',
 'HINDALCO',
 'HINDUNILVR',
 'CAIRN',
 'ICICIBANK',
 'INFY',
 'UNITECH',
 'ITC',
 'RPL',
 'LT',
 'MARUTI',
 'M&M',
 'IDEA',
 'NATIONALUM',
 'ONGC',
 'STER',
 'PNB',
 'RANBAXY',
 'RELINFRA',
 'RELIANCE',
 'SAIL',
 'SATYAMCOMP',
 'SBIN',
 'SIEMENS',
 'SUNPHARMA',
 'SUZLON',
 'TATAPOWER',
 'RCOM',
 'TATAMOTORS',
 'TCS',
 'TATASTEEL',
 'TATACOMM',
 'WIPRO',
 'ZEEL',
 'DLF',
 'POWERGRID',
 'RPOWER',
 'RELCAPITAL',
 'AXISBANK',
 'JINDALSTEL',
 'IDFC',
 'JPASSOCIAT',
 'KOTAKBANK',
 'SESAGOA',
 'HEROMOTOCO',
 'COALINDIA',
 'ASIANPAINT',
 'BANKBARODA',
 'LUPIN',
 'ULTRACEMCO',
 'VEDL',
 'INDUSINDBK',
 'NMDC',
 'SSLT',
 'MCDOWELL-N',
 'TECHM',
 'YESBANK',
 'BOSCHLTD',
 'ADANIPORTS',
 'AUROPHARMA',
 'INFRATEL',
 'EICHERMOT',
 'TATAMTRDVR',
 'IBULHSGFIN',
 'IOC',
 'BAJFINANCE',
 'HINDPETRO',
 'UPL',
 'BAJAJFINSV',
 'TITAN',
 'JSWSTEEL',
 'BRITANNIA',
 'NESTLEIND',
 'SHREECEM',
 'HDFCLIFE',
 'DIVISLAB',
 'SBILIFE',
 'TATACONSUM',
 'APOLLOHOSP',
 'ADANIENT',
 'LTIM',
 'SHRIRAMFIN',
 'BEL',
 'TRENT',
 'ETERNAL',
 'JIOFIN',
 'INDIGO',
 'MAXHEALTH',
 'TMPV']

In [28]:
(nifty50.query("symbol== 'TMPV'"))

,rank,symbol,company_name,industry,equity_capital,free_float_market_cap,weight,beta,r2,volatility,monthly_return,impact_cost,report_date,source_file
10643,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365045e+09,85404.380630,0.725828,1.293869,0.308866,0.826712,-39.723611,0.02,2025-10-01,nifty50_oct25.csv
10693,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365045e+09,74322.641483,0.623889,1.295063,0.274269,1.560889,-12.975610,0.02,2025-11-01,nifty50_nov25.csv
10743,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365159e+09,76601.370830,0.644577,1.294454,0.522485,1.045160,2.956839,0.02,2025-12-01,nifty50_dec25.csv
10793,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365159e+09,72993.900000,0.630000,1.290000,0.290000,1.400000,-4.710000,0.02,2026-01-01,nifty50_jan26.csv
10843,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365159e+09,79791.790000,0.700000,1.210000,0.270000,1.730000,9.310000,0.02,2026-02-01,nifty50_feb26.csv
10893,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365251e+09,61860.550000,0.610000,1.350000,0.390000,2.860000,-22.590000,0.02,2026-03-01,nifty50_mar26.csv
10943,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365251e+09,71331.770000,0.650000,1.370000,0.400000,2.400000,15.310000,0.02,2026-04-01,nifty50_apr26.csv
10993,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365251e+09,82264.920000,0.760000,1.480000,0.420000,2.340000,15.330000,0.02,2026-05-01,nifty50_may26.csv
11043,44,TMPV,Tata Motors Passenger Vehicles Ltd.,Passenger Cars & Utility Vehicles,7.365662e+09,73401.590000,0.670000,1.510000,0.400000,2.410000,-10.590000,0.02,2026-06-01,nifty50_jun26.csv

In [29]:
(
    nifty50
    [["symbol", "industry"]]
    .set_index("symbol")
    .to_dict()
)

{'industry': {'ABB': nan,
  'ACC': 'Cement & Cement Products',
  'BAJAJAUTO': 'Two & Three Wheelers',
  'BHARTIARTL': 'Telecom Services',
  'BHEL': nan,
  'BPCL': 'Refineries & Marketing',
  'CIPLA': 'Pharmaceuticals',
  'NTPC': 'Power Generation',
  'DRREDDY': 'Pharmaceuticals',
  'GAIL': 'Gas',
  'GLAXO': 'Pharmaceuticals',
  'GRASIM': 'Cement & Cement Products',
  'AMBUJACEM': 'Cement & Cement Products',
  'HCLTECH': 'Computers - Software & Consulting',
  'HDFC': 'Housing Finance',
  'HDFCBANK': 'Private Sector Bank',
  'HEROHONDA': 'Two & Three Wheelers',
  'HINDALCO': 'Aluminium',
  'HINDUNILVR': nan,
  'CAIRN': 'Oil Exploration & Production',
  'ICICIBANK': 'Private Sector Bank',
  'INFY': 'Computers - Software & Consulting',
  'UNITECH': nan,
  'ITC': nan,
  'RPL': 'Refineries & Marketing',
  'LT': nan,
  'MARUTI': 'Passenger Cars & Utility Vehicles',
  'M&M': 'Passenger Cars & Utility Vehicles',
  'IDEA': 'Telecom Services',
  'NATIONALUM': 'Aluminium',
  'ONGC': 'Oil Exploration & Production',
  'STER': nan,
  'PNB': 'Public Sector Bank',
  'RANBAXY': 'Pharmaceuticals',
  'RELINFRA': 'Power',
  'RELIANCE': 'Refineries & Marketing',
  'SAIL': 'Iron & Steel',
  'SATYAMCOMP': 'Computers - Software & Consulting',
  'SBIN': 'Public Sector Bank',
  'SIEMENS': nan,
  'SUNPHARMA': 'Pharmaceuticals',
  'SUZLON': nan,
  'TATAPOWER': 'Power',
  'RCOM': 'Telecom Services',
  'TATAMOTORS': 'Passenger Cars & Utility Vehicles',
  'TCS': 'Computers - Software & Consulting',
  'TATASTEEL': 'Iron & Steel',
  'TATACOMM': 'Telecom Services',
  'WIPRO': 'Computers - Software & Consulting',
  'ZEEL': nan,
  'DLF': nan,
  'POWERGRID': 'Power Transmission',
  'RPOWER': 'Power',
  'RELCAPITAL': 'Finance',
  'AXISBANK': 'Private Sector Bank',
  'JINDALSTEL': 'Iron & Steel',
  'IDFC': 'Financial Institution',
  'JPASSOCIAT': nan,
  'KOTAKBANK': 'Private Sector Bank',
  'SESAGOA': 'Mining',
  'HEROMOTOCO': 'Two & Three Wheelers',
  'COALINDIA': 'Coal',
  'ASIANPAINT': nan,
  'BANKBARODA': 'Public Sector Bank',
  'LUPIN': 'Pharmaceuticals',
  'ULTRACEMCO': 'Cement & Cement Products',
  'VEDL': 'Aluminium',
  'INDUSINDBK': 'Private Sector Bank',
  'NMDC': 'Mining',
  'SSLT': 'Mining',
  'MCDOWELL-N': nan,
  'TECHM': 'Computers - Software & Consulting',
  'YESBANK': 'Public Sector Bank',
  'BOSCHLTD': nan,
  'ADANIPORTS': nan,
  'AUROPHARMA': 'Pharmaceuticals',
  'INFRATEL': 'Telecom Equipment',
  'EICHERMOT': 'Two & Three Wheelers',
  'TATAMTRDVR': 'Passenger Cars & Utility Vehicles',
  'IBULHSGFIN': 'Housing Finance',
  'IOC': 'Refineries & Marketing',
  'BAJFINANCE': 'NBFC',
  'HINDPETRO': 'Refineries & Marketing',
  'UPL': nan,
  'BAJAJFINSV': 'Holding Company',
  'TITAN': nan,
  'JSWSTEEL': 'Iron & Steel',
  'BRITANNIA': nan,
  'NESTLEIND': nan,
  'SHREECEM': 'Cement & Cement Products',
  'HDFCLIFE': 'Life Insurance',
  'DIVISLAB': 'Pharmaceuticals',
  'SBILIFE': 'Life Insurance',
  'TATACONSUM': nan,
  'APOLLOHOSP': nan,
  'ADANIENT': nan,
  'LTIM': 'Computers - Software & Consulting',
  'SHRIRAMFIN': 'NBFC',
  'BEL': nan,
  'TRENT': nan,
  'ETERNAL': nan,
  'JIOFIN': 'Investment Company',
  'INDIGO': nan,
  'MAXHEALTH': nan,
  'TMPV': 'Passenger Cars & Utility Vehicles'}}

In [30]:
nifty50A= (
    pd.read_parquet(
        "../data/processed/nifty50_history.parquet",
        # parse_dates=["Date"],
    )
    .assign(
            company_name= lambda df_: df_["symbol"].map(SYMBOL_TO_COMPANY).fillna(df_["company_name"]),
            symbol= lambda df_: df_["company_name"].map(SYMBOL_TO_COMPANY).fillna(df_["company_name"]),

    )
)

nifty50A.head()

,rank,symbol,company_name,industry,equity_capital,free_float_market_cap,weight,beta,r2,volatility,monthly_return,impact_cost,report_date,source_file
0,1,ABB Ltd.,ABB Ltd.,Electrical Equipment,4.238168e+08,23732.0,0.80,0.86,0.48,3.14,-25.94,0.15,2008-01-01,nifty50_jan08.csv
1,2,ACC Ltd.,ACC Ltd.,Cement & Cement Products,1.876243e+09,14411.0,0.49,0.89,0.36,3.73,-25.05,0.17,2008-01-01,nifty50_jan08.csv
2,3,Bajaj Auto Ltd.,Bajaj Auto Ltd.,Automobiles - 2 and 3 wheelers,1.011835e+09,23870.0,0.80,0.64,0.25,4.75,-10.23,0.17,2008-01-01,nifty50_jan08.csv
3,4,Bharti Airtel Ltd.,Bharti Airtel Ltd.,Telecommunication - Services,1.897883e+10,163000.0,5.49,0.89,0.42,3.08,-13.80,0.15,2008-01-01,nifty50_jan08.csv
4,5,Bharat Heavy Electricals Ltd.,Bharat Heavy Electricals Ltd.,Electrical Equipment,4.895200e+09,100856.0,3.40,1.10,0.58,3.34,-20.44,0.11,2008-01-01,nifty50_jan08.csv